### ISSUE TITLE
Changes Before Live

### ISSUE THREAD

**Issue by rafaelsinger** [bccss/hacktheheights#16]
Need to make these changes before making this our live version of the site:
- make favicon transparent
- add team section w/ photos - need design and implementation
- revise FAQs and answers
- update about cards
- make register link functional
- make contact form
- center the landing splash
- make the navbar dropdown on mobile look better (julia?)
- make sure fonts are all uniform
- upload actual photos for previous events in photo carousel
- add a title for this section
- add links to socials in the footer
- standardize padding/margin for website (julia?)
- figure out layout for the page?
- make events page actually have functionality + be up to date
- landing splash is not responsive for medium viewports

**Comment by hunterschep** [comment]
Registration link is now functional 
Landingsplash has been updated
